import { THEME } from '../constants/theme';

/**
 * Static, honest signal-routing diagram that mirrors the actual node graph
 * in `SynthEngine`. Purely presentational SVG.
 */
export function SignalChainDiagram() {
  return (
    <section
      className="border border-[#1a1a2e] rounded-sm overflow-hidden panel-glow-cyan"
      aria-label="Signal routing"
    >
      <header className="px-2 py-1 border-b border-[#1a1a2e]">
        <h2 className="text-[9px] text-[#00e5ff] font-mono opacity-70">
          CIRCUIT // SIGNAL ROUTING
        </h2>
      </header>
      <div className="p-2" style={{ background: 'rgba(10,10,15,0.6)' }}>
        <svg viewBox="0 0 200 92" className="w-full h-20" role="img" aria-hidden="true">
          <rect
            x="2"
            y="5"
            width="36"
            height="20"
            rx="2"
            fill="none"
            stroke={THEME.green}
            strokeWidth="0.8"
          />
          <text
            x="20"
            y="18"
            textAnchor="middle"
            fill={THEME.green}
            fontSize="6"
            fontFamily="monospace"
          >
            OSC1
          </text>
          <rect
            x="2"
            y="38"
            width="36"
            height="20"
            rx="2"
            fill="none"
            stroke={THEME.cyan}
            strokeWidth="0.8"
          />
          <text
            x="20"
            y="51"
            textAnchor="middle"
            fill={THEME.cyan}
            fontSize="6"
            fontFamily="monospace"
          >
            OSC2
          </text>

          <rect
            x="52"
            y="20"
            width="30"
            height="22"
            rx="2"
            fill="none"
            stroke={THEME.purple}
            strokeWidth="0.8"
          />
          <text
            x="67"
            y="34"
            textAnchor="middle"
            fill={THEME.purple}
            fontSize="5"
            fontFamily="monospace"
          >
            MIX
          </text>
          <rect
            x="94"
            y="20"
            width="30"
            height="22"
            rx="2"
            fill="none"
            stroke={THEME.amber}
            strokeWidth="0.8"
          />
          <text
            x="109"
            y="34"
            textAnchor="middle"
            fill={THEME.amber}
            fontSize="5"
            fontFamily="monospace"
          >
            VCF
          </text>
          <rect
            x="136"
            y="20"
            width="30"
            height="22"
            rx="2"
            fill="none"
            stroke={THEME.pink}
            strokeWidth="0.8"
          />
          <text
            x="151"
            y="34"
            textAnchor="middle"
            fill={THEME.pink}
            fontSize="5"
            fontFamily="monospace"
          >
            FX
          </text>
          <rect
            x="178"
            y="23"
            width="18"
            height="16"
            rx="8"
            fill="none"
            stroke={THEME.green}
            strokeWidth="0.8"
          />
          <text
            x="187"
            y="34"
            textAnchor="middle"
            fill={THEME.green}
            fontSize="5"
            fontFamily="monospace"
          >
            OUT
          </text>

          <rect
            x="94"
            y="62"
            width="30"
            height="16"
            rx="2"
            fill="none"
            stroke={THEME.teal}
            strokeWidth="0.8"
            strokeDasharray="2"
          />
          <text
            x="109"
            y="73"
            textAnchor="middle"
            fill={THEME.teal}
            fontSize="5"
            fontFamily="monospace"
          >
            LFO
          </text>

          <line
            x1="38"
            y1="15"
            x2="52"
            y2="27"
            stroke={THEME.green}
            strokeWidth="0.5"
            opacity="0.6"
          />
          <line
            x1="38"
            y1="48"
            x2="52"
            y2="35"
            stroke={THEME.cyan}
            strokeWidth="0.5"
            opacity="0.6"
          />
          <line
            x1="82"
            y1="31"
            x2="94"
            y2="31"
            stroke={THEME.purple}
            strokeWidth="0.5"
            opacity="0.6"
          />
          <line
            x1="124"
            y1="31"
            x2="136"
            y2="31"
            stroke={THEME.amber}
            strokeWidth="0.5"
            opacity="0.6"
          />
          <line
            x1="166"
            y1="31"
            x2="178"
            y2="31"
            stroke={THEME.pink}
            strokeWidth="0.5"
            opacity="0.6"
          />
          <line
            x1="109"
            y1="62"
            x2="109"
            y2="42"
            stroke={THEME.teal}
            strokeWidth="0.5"
            opacity="0.4"
            strokeDasharray="2"
          />
        </svg>
      </div>
    </section>
  );
}
